name: tenant_connect
description: "TenantConnect - Direct tenant-to-tenant property handover platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  photo_view: ^0.15.0

  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.2.4

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

  # Networking
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.19.0
  uuid: ^4.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

  # Location
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # UI Components
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0

  # Chat
  stream_chat_flutter: ^8.0.0

  # Maps
  google_maps_flutter: ^2.6.1

  # Push Notifications
  flutter_local_notifications: ^17.1.2

  # File handling
  file_picker: ^8.0.0+1

  # Loading indicators
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  integration_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
